### ISSUE TITLE
Label and concatenation of genbank file from taxonomy ID

### ISSUE THREAD

**Issue by abelardoacm** [abelardoacm/ssDNA_viral_pangenomics#2]
Algorithms to find pangenomic clusters are based on "set theory". Proteins are classified as members of the **core, shell or cloud clusters** according to their **prevalence** in the proteomes analyzed. 

One of the **assumptions** of the program before evaluating protein's prevalence is **that the input files contain only complete genomes**. This gives rise to the fact that the **pangenomic clusters can be underestimated** when this is not fulfilled.

Viral genomes present a potential source of underestimation.

## **Segmented genomes**

There are families whose genome exists in **physically separated pieces**, providing modularity to the way of packaging genetic information. If the input of the pangenomic analysis contains one file per genomic segment and not one per species, **the algorithm interprets that the genes of one segment are not related to the other**, thus considering them as different species. This results in **non existent pangenomic cores** for segmented families.

so we need to concatenate some files...

*NOTE: Not every genome is submitted in different files, some are real complete genomes.*
*NOTE: Not every segmented genome consist in the same number of pieces.*

<p align="center">
  <img src="https://viralzone.expasy.org/resources/Nanovirus%5Fgenome.jpg">
</p>

## **Previous strategy:**

It consisted in the **concatenation departing from the filenames**, where different files were concatenated if the [**text distances**](https://pypi.org/project/textdistance/) **between its names is less than one word or letter**. 

A python script was developed and used, however it derived both in the **over-concatenation** and **sub-concatenation** of files. 

Since name assignment is heterogeneous, the concatenation strategy cannot be based on filenames.

## [**Current strategy:**](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/bin/Concatenation_from_taxid.pl)

Departs from the observation that downloaded genbank files contain unique taxonomic IDs, shared between segments from the same viral species. A perl script is being coded, and it already performs the extractions of taxids from individual genbank files (previously partitioned with [1_Set_family_files_from_raw_genbank.sh](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/bin/1_Set_family_files_from_raw_genbank.sh)), as the following computational task:

-  [Concatenation_from_taxid.pl](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/bin/Concatenation_from_taxid.pl)

    - **Input:** A species individual genbank file
    - **Output:** Unique taxid found with perl regex match.

For example, the 21st line of the following partial genbank file contains the unique taxid:
``` 
1          LOCUS                   NC_001928               2632 bp    DNA     circular VRL 13-AUG-2018
2          DEFINITION           Abutilon mosaic virus subgenome DNA A.
3          ACCESSION          NC_001928
4          VERSION               NC_001928.2
5          KEYWORDS          RefSeq; circular; coat protein; structural protein.
6          SOURCE                 Abutilon mosaic virus
7          ORGANISM           Abutilon mosaic virus
8                   Viruses; Monodnaviria; Shotokuvirae; Cressdnaviricota;
9                    Repensiviricetes; Geplafuvirales; Geminiviridae; Begomovirus.
10        REFERENCE          (bases 1 to 2632)
11        AUTHORS               Frischmuth,T., Zimmat,G. and Jeske,H.
12        TITLE                    The nucleotide sequence of abutilon mosaic virus reveals
13                                      prokaryotic as well as eukaryotic features
14       JOURNAL               Virology 178 (2), 461-468 (1990)
15       PUBMED                 2219703
16       FEATURES             Location/Qualifiers
17            source  1..2632
18                          /organism="Abutilon mosaic virus"
19                          /mol_type="genomic DNA"
20                          /host="Abutilon sellovianum REGEL"
21                          /db_xref="taxon:10815"
22                          /segment="DNA A"
23           gene            complement(order(1571..2632,1..9))
24                          /gene="ORF C1"
25                          /locus_tag="AbMVsAp1"
26                          /db_xref="GeneID:956371"
```
## **Desired enhancement**

It is desired that this script operates from the original  downloaded genbank file, leading to the following computational task:

- **Input:** A whole family genbank file of complete and segmented genomes with unique and shared taxonomic IDs
- **Output:** A new folder containing one complete genome file per taxonomic ID.

in brief...

1. Find the line containing the taxid
2. Label the partitioned file with its taxid
3. Concatenate files with equal labels in a unique file

Sample input [**Geminiviridae.gbk**](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/data/Raw_database/Geminiviridae.gb) that splits into: 

```
Abutilon-Brazil-virus-DNA-A-segment-complete-sequence_NC_014138_taxid_665102_.gbk
Abutilon-Brazil-virus-DNA-B-segment-complete-sequence_NC_014139_taxid_665102_.gbk
Abutilon-golden-mosaic-Yucatan-virus-isolate-Conkal-2007-segment-A_NC_038438_taxid_1312723_.gbk
Abutilon-mosaic-Bolivia-virus-DNA-A-complete-genome_NC_015045_taxid_932071_.gbk
Abutilon-mosaic-Bolivia-virus-DNA-B-complete-genome_NC_015048_taxid_932071_.gbk
Abutilon-mosaic-Brazil-virus-DNA-A-complete-genome_NC_016574_taxid_1046572_.gbk
Abutilon-mosaic-Brazil-virus-DNA-B-complete-genome_NC_016577_taxid_1046572_.gbk
Abutilon-mosaic-virus-subgenome-DNA-A_NC_001928_taxid_10815_.gbk
Abutilon-mosaic-virus-subgenome-DNA-B_NC_001929_taxid_10815_.gbk
African-cassava-mosaic-virus-isolate-West-Kenyan-844-segment-DNA1_NC_001467_taxid_10817_.gbk
African-cassava-mosaic-virus-isolate-West-Kenyan-844-segment-DNA2_NC_001468_taxid_10817_.gbk
Ageratum-enation-virus-complete-genome_NC_003434_taxid_188333_.gbk
Ageratum-leaf-curl-Cameroon-virus-complete-genome_NC_014645_taxid_912033_.gbk
Ageratum-leaf-curl-virus--G52-complete-genome_NC_006384_taxid_298650_.gbk
Ageratum-yellow-vein-China-virus-Hn2-complete-genome-isolate_NC_004090_taxid_222078_.gbk
Ageratum-Yellow-vein-China-virus--OX1-complete-genome_NC_021202_taxid_1329380_.gbk
Ageratum-yellow-vein-Hualian-virus-Taiwan-Hsinchu-tom-2003-DNA-A_NC_010812_taxid_437063_.gbk
Ageratum-yellow-vein-Hualian-virus-Taiwan-Hualian4-2000-segment_NC_038913_taxid_437061_.gbk
Ageratum-yellow-vein-Sri-Lanka-virus-segment-A-complete-genome_NC_002981_taxid_222079_.gbk
Ageratum-yellow-vein-Taiwan-virus-complete-genome_NC_004627_taxid_222441_.gbk
Ageratum-yellow-vein-virus-complete-genome_NC_004626_taxid_44560_.gbk

```

Sample output:

```
Abutilon-Brazil-virus-DNA-A-segment-complete-sequence.gbk            >>  complete_genome_taxid_2384761.gbk
Abutilon-Brazil-virus-DNA-B-segment-complete-sequence.gbk            >> complete_genome_taxid_2384761.gbk
Abutilon-golden-mosaic-Yucatan-virus-isolate-Conkal-2007-segment-A.gbk            >> complete_genome_taxid_187625.gbk
Abutilon-mosaic-Bolivia-virus-DNA-A-complete-genome.gbk            >> complete_genome_taxid_222232.gbk
Abutilon-mosaic-Bolivia-virus-DNA-B-complete-genome.gbk            >> complete_genome_taxid_222232.gbk
Abutilon-mosaic-Brazil-virus-DNA-A-complete-genome.gbk            >> complete_genome_taxid_222232.gbk
Abutilon-mosaic-Brazil-virus-DNA-B-complete-genome.gbk            >> complete_genome_taxid_222232.gbk
Abutilon-mosaic-virus-subgenome-DNA-A.gbk            >> complete_genome_taxid_162313.gbk
Abutilon-mosaic-virus-subgenome-DNA-B.gbk            >> complete_genome_taxid_162313.gbk
African-cassava-mosaic-virus-isolate-West-Kenyan-844-segment-DNA1.gbk            >> complete_genome_taxid_162245.gbk
African-cassava-mosaic-virus-isolate-West-Kenyan-844-segment-DNA2.gbk            >> complete_genome_taxid_162245.gbk
Ageratum-enation-virus-complete-genome.gbk            >> complete_genome_taxid_162315.gbk
Ageratum-leaf-curl-Cameroon-virus-complete-genome.gbk            >> complete_genome_taxid_162319.gbk
Ageratum-leaf-curl-virus--G52-complete-genome.gbk            >> complete_genome_taxid_162321.gbk
Ageratum-yellow-vein-China-virus-Hn2-complete-genome-isolate.gbk            >> complete_genome_taxid_162333.gbk
```

Note that a proper name for the concatenation output file, linked to the organism's name is still missing and renaming should constitute a upcoming task.

**Comment by NellyJazminPC** [comment]
A way to find the same files for this specific TaxID and concatened in one file
`ls | grep *taxid_51673_.gbk > cat taxid_51673_.gbk`

**Comment by NellyJazminPC** [comment]
Another way

`var_taxid < "here it go the list of the taxid uniques, no repets"`

`ls | grep *$var_taxid* > cat *$var_taxid_.gbk`

**Comment by camillethuyentruong** [comment]
Puedes definir la variable taxid (buscando el campo *taxid_51673_.gbk en los títulos) y usarla en la función con `grep` y `cat`

**Comment by NellyJazminPC** [comment]
Another way to obtained just the list of unique taxid

`ls | cut -d_ -f4- | sort -u`

to send this list in a variable 

`var_tax_id="$(cat list_input.txt| cut -d_ -f4- |sort -u)"`

list_input file contain the *Sample input Geminiviridae.gbk* that it is in this issue in the description 

or 

`var_tax_id="$(ls | cut -d_ -f4- |sort -u)"`

**Comment by camillethuyentruong** [comment]
Usando loop

`for i in **STRING**; do echo Filename : "$i";echo;cat "$i"; done`

**Comment by camillethuyentruong** [comment]
Ejemplos usando `awk`
https://unix.stackexchange.com/questions/556427/filter-500-files-with-awk-then-cat-results-to-single-file

https://www.tecmint.com/use-linux-awk-command-to-filter-text-string-in-files/

**Comment by bgrueda** [comment]
https://stackoverflow.com/questions/61016760/combine-the-content-of-couple-of-files-with-shared-part-of-file-name

Maybe this could be useful for this purpose
