### ISSUE TITLE
Markdown summary and R figures are missing

### ISSUE THREAD

**Issue by AliciaMstt** [abelardoacm/ssDNA_viral_pangenomics#4]
Remember you should include a markdown summary with a short discussion and showing a figure made in R. Besides showing the figure, it should be clear with which script was it done.

**Comment by abelardoacm** [comment]
thanks a lot !!

I'll work on it as soon as possible

**Comment by abelardoacm** [comment]
:heavy_check_mark:  DONE, also I made [ABriefRepoHistory.md](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/ABriefRepoHistory.md), and a new [README.md](https://github.com/abelardoacm/ssDNA_viral_pangenomics/tree/main/bin) merely for bin.
