### ISSUE TITLE
Repo comments

### ISSUE THREAD

**Issue by solnavss** [abelardoacm/ssDNA_viral_pangenomics#5]
Hi, I have some comments that I hope will help you to improve your repo:

- [x] Add open-source license (https://choosealicense.com/)
- [x] Include in your diagram (navigation guide) headers with the steps you mention below, you could even list them as follow:

1. From raw to filtered database
2. From filtered database to distance matrices
...

- [x] Add some references in the Introduction

Some tips:
If the scripts are of your creation, you can add the following lines at the beginning: -example-

```
#!/usr/bin/python
# ---------------------------------------------
# Name - git username
# Institution
# Date
# A brief description of what the program does
# ---------------------------------------------
Python code...
```

**Comment by abelardoacm** [comment]
Thanks a lot !!

...I'll work on it the next days :computer:

**Comment by abelardoacm** [comment]
DONE, I've made the suggested improvements. Thank you again

**Comment by abelardoacm** [comment]
:heavy_check_mark:  DONE, also I made [ABriefRepoHistory.md](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/ABriefRepoHistory.md), and a new [README.md](https://github.com/abelardoacm/ssDNA_viral_pangenomics/tree/main/bin) merely for bin.
