### ISSUE TITLE
Mash dist output transformation

### ISSUE THREAD

**Issue by abelardoacm** [abelardoacm/ssDNA_viral_pangenomics#7]
#### Background
Computation of distance matrices is a key step in pre-pangenomic data manipulation since it allows for pre-clustering the input. So far this repository workflow includes an AF-method to perform this task (see: [Cumulative Phase Spectra Fourier Analysis](https://github.com/YaulabTsinghua/The-central-moments-and-covariance-vector-of-cumulative-Fourier-Transform-power-and-phase-spectra.git)), **but** as stated in the [main README](https://github.com/abelardoacm/ssDNA_viral_pangenomics) file, this step is way more customizable. For that purpose I am trying to include an alternative method to obtain a paired distance matrix.
#
#### [Mash](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4915045/) 
is an AF-method that estimates evolutionary distances. The tool uses the **MinHash algorithm** to reduce the input sequences to small “sketches,” which allow fast distance estimations with low storage and memory requirements. To create a “sketch,” each k-mer in a sequence is *hashed*, which creates a pseudorandom identifier (hash). By sorting these hashes, a small subset from the top of the sorted list can represent the entire sequence (min-hashes). Two sketches are compared to provide an estimate of the Jaccard index (i.e., the fraction of shared hashes) and the Mash distance, which estimates the rate of sequence mutation under an evolutionary model ([Zielezinski *et al*. 2019]( https://doi.org/10.1186/s13059-019-1755-7)).
#
### Issue: Output re-formatting
Until now, I have a working installation of mash which is proven to work with sample data. These are the symbolic commands I use when working with my data.

1.-`./mash sketch -s 400 -k 16 -o anytaxon <path_to_genomes_folder>/*.fn`
- 1st INPUT: All fasta files of *anytaxon* genomes
- 1st OUTPUT: A file **anytaxon.msh** containing the MinHash sketches of each genome
the output for this step does not need manipulation, however...

2.-`./mash dist anytaxon.msh anytaxon.msh`
- 2nd INPUT: anytaxon.msh file containing sketches
- 2nd OUTPUT: all paired distances in stdout as follows: 
```
Vernonia-yellow-vein-virus_taxid_367061.fn	Vernonia-yellow-vein-virus_taxid_367061.fn	0	0	400/400
Vigna-yellow-mosaic-virus_taxid_1312724.fn	Vernonia-yellow-vein-virus_taxid_367061.fn	0.331301	0.000124398	1/400
Vinca-leaf-curl-virus_taxid_1170656.fn	Vernonia-yellow-vein-virus_taxid_367061.fn	0.231331	2.85164e-22	5/400
Watermelon-chlorotic-stunt-virus_taxid_35341.fn	Vernonia-yellow-vein-virus_taxid_367061.fn	0.331301	0.0001705	1/400
West-African-Asystasia-virus-1_taxid_1046573.fn	Vernonia-yellow-vein-virus_taxid_367061.fn	0.331301	0.000169349	1/400
+ 200,000 lines 
 ```
paired distances are available from standar output, however they are printed as a list of comparisons instead of a distance matrix. As discussed in marbl/Mash#119 , the indicated function would be `mash triangle` but it does not performs as expected neither.

#### Desired OUTPUT
The desired OUTPUT would have the following format so it can merge to current workflow:
```
	         taxid_665102	taxid_1312723	taxid_932071	taxid_1046572	taxid_10815
taxid_665102	0	4356205.51744751	324815.355607559	153250.356092081	161267.013786438
taxid_1312723	4356205.51744751	0	4622258.42181764	4384079.64349084	4243907.13617956
taxid_932071	324815.355607559	4622258.42181764	0	278906.569940636	450435.647278679
taxid_1046572	153250.356092081	4384079.64349084	278906.569940636	0	209748.162789732
taxid_10815	161267.013786438	4243907.13617956	450435.647278679	209748.162789732	0
```
which is a matrix with taxids as row and column names

I'm working on a strategy based on R, previously sending stdout to a comma separated file. Then reading fields to build coordinates and distances.

In brief, I'm trying to go from **2nd Output** to **desired Output**

**Comment by AliciaMstt** [comment]
Try the solution suggested here:

https://stackoverflow.com/questions/9617348/reshape-three-column-data-frame-to-matrix-long-to-wide-format

**Comment by arihelrnan** [comment]
In previous suggestion, you can use option `pivot_wider` and writte your second colum in the option  `names_from = `. This argument make a matrix with this data.

**Comment by redgcko7** [comment]
To change the names of the taxonID to make it more succinct, we used regular expressions, then we used the pivot_wider command from tidyr to make the matrix:

```
library("dplyr")
library("tidyr")

MashDistOut <- read.csv("MashDistOut.csv", header = F)

MashDistOut$V1 <- gsub("^.*.taxid", replacement = "taxid", MashDistOut$V1) %>%
    gsub(".fn", replacement = "", .)

MashDistOut$V2 <- gsub("^.*.taxid", replacement = "taxid", MashDistOut$V1) %>%
  gsub(".fn", replacement = "", .)

Mash.dist.mx <- select(MashDistOut, V1:V3) %>%
    pivot_wider(., names_from = V2, values_from = V3)
```

**Comment by abelardoacm** [comment]
Thank you very much @AliciaMstt , @arihelrnan , and @redgcko7. I've been working on a script to implement the proposed solutions, although it has not been completely merged to the main pipeline and master-script. You can check it here: [Mash_dist_to_matrix.r](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/bin/Mash_dist_to_matrix.r)
